// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9vmEQJdK_HHn3Meg77ypMo1ETuoRkgH4',
    appId: '1:740539884031:web:002d1eeb4e6bf45adb87ca',
    messagingSenderId: '740539884031',
    projectId: 'tracktruck-ad7d8',
    authDomain: 'tracktruck-ad7d8.firebaseapp.com',
    storageBucket: 'tracktruck-ad7d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfBfisw8-SNsDEZaB0jAZHuBinqZj8F40',
    appId: '1:740539884031:android:e3349ee27c9db2a2db87ca',
    messagingSenderId: '740539884031',
    projectId: 'tracktruck-ad7d8',
    storageBucket: 'tracktruck-ad7d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_L3ymr1J-SnvS7Y_qdwImG9y4-thTtnM',
    appId: '1:740539884031:ios:6421f1ae1fbfefc4db87ca',
    messagingSenderId: '740539884031',
    projectId: 'tracktruck-ad7d8',
    storageBucket: 'tracktruck-ad7d8.appspot.com',
    iosBundleId: 'com.example.tracktruck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_L3ymr1J-SnvS7Y_qdwImG9y4-thTtnM',
    appId: '1:740539884031:ios:6421f1ae1fbfefc4db87ca',
    messagingSenderId: '740539884031',
    projectId: 'tracktruck-ad7d8',
    storageBucket: 'tracktruck-ad7d8.appspot.com',
    iosBundleId: 'com.example.tracktruck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9vmEQJdK_HHn3Meg77ypMo1ETuoRkgH4',
    appId: '1:740539884031:web:50e89dcc7b62fb88db87ca',
    messagingSenderId: '740539884031',
    projectId: 'tracktruck-ad7d8',
    authDomain: 'tracktruck-ad7d8.firebaseapp.com',
    storageBucket: 'tracktruck-ad7d8.appspot.com',
  );

}